apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  selector:
    matchLabels:
      app: nodejs-hello-world
  replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nodejs-hello-world
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nodejs-hello-world
        image: ajdevopssolutions/nodejs-hello-world:latest
        ports:
        - containerPort:  80
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 100Mi
      #     limits:
      #       cpu: 100m
      #       memory: 100Mi
      #   livenessProbe:
      #     tcpSocket:
      #       port: 80
      #     initialDelaySeconds: 5
      #     timeoutSeconds: 5
      #     successThreshold: 1
      #     failureThreshold: 3
      #     periodSeconds: 10
      #   readinessProbe:
      #     httpGet:
      #       path: /_status/healthz
      #       port: 80
      #     initialDelaySeconds: 5
      #     timeoutSeconds: 2
      #     successThreshold: 1
      #     failureThreshold: 3
      #     periodSeconds: 10
      #   env:
      #   - name: DB_HOST
      #     valueFrom:
      #       configMapKeyRef:
      #         name: MYAPP
      #         key: DB_HOST
      #   ports:
      #   - containerPort:  80
      #     name:  MYAPP
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai
      # restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world-service
spec:
  selector:
    app: nodejs-hello-world
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: nodejs-hello-world
    protocol: TCP
    port: 3000
    targetPort: 8080
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30020